default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: Danebook_development
  timeout: 5000

test:
  <<: *default
  database: Danebook_test
  timeout: 5000

production:
  <<: *default
  database: Danebook_production
  timeout: 5000
