default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: Spacebook_development
  timeout: 5000

test:
  <<: *default
  database: Spacebook_test
  timeout: 5000

production:
  <<: *default
  database: Spacebook_production
  timeout: 5000
